<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_samsungGalaxyS23Ultra</name>
   <tag></tag>
   <elementGuidId>1db2b07e-2649-4585-b919-085a1091b855</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]/li[2]/div[1]/h4[1]/a[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) [class=&quot;products__title&quot;] > a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/product/samsung-galaxy-s23-ultra' and (text() = 'Samsung Galaxy S23 Ultra' or . = 'Samsung Galaxy S23 Ultra')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Samsung Galaxy S23 Ultra&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/product/samsung-galaxy-s23-ultra</value>
      <webElementGuid>dea07a69-13f0-47cc-a1aa-31f3ff38d101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>0dd498f8-2cf8-4ab4-b52c-5883f56d5e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Samsung Galaxy S23 Ultra</value>
      <webElementGuid>d6761c12-3cb2-4637-81be-110fb44229d6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
