<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>button_continueToShipping</name>
   <tag></tag>
   <elementGuidId>19b64c0c-6d0d-4405-8eea-f1b3bc4a848d</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[3]/button[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[class=&quot;MuiButtonBase-root\ MuiButton-root\ MuiButton-contained\ MuiButton-containedPrimary\ MuiButton-sizeLarge\ MuiButton-containedSizeLarge\ MuiButton-root\ MuiButton-contained\ MuiButton-containedPrimary\ MuiButton-sizeLarge\ MuiButton-containedSizeLarge\ css-110xwq5&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeLarge MuiButton-containedSizeLarge MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeLarge MuiButton-containedSizeLarge css-110xwq5' and @type = 'submit' and (text() = 'Continue to shipping' or . = 'Continue to shipping')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Continue to shipping&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeLarge MuiButton-containedSizeLarge MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeLarge MuiButton-containedSizeLarge css-110xwq5</value>
      <webElementGuid>d860edbf-dc3d-43e4-ac45-13b820525fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c8d6ed5b-2bc4-4342-baea-30d4ad2a7776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue to shipping</value>
      <webElementGuid>a8cca13a-150d-472e-b33a-afbbfd1cfdf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f64e699d-9f5e-41c7-8b59-d7ef166cc6c6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
