<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_iphone16e</name>
   <tag></tag>
   <elementGuidId>113616e0-08e8-436c-9c9e-5c83723e1eed</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]/li[2]/div[1]/h4[1]/a[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) [class=&quot;products__title&quot;] > a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/product/apple-iphone-16e' and (text() = 'iPhone 16e' or . = 'iPhone 16e')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;iPhone 16e&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/product/apple-iphone-16e</value>
      <webElementGuid>b219bcfe-08ee-4e5e-9e24-de4cd94d9eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>0dd498f8-2cf8-4ab4-b52c-5883f56d5e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>iPhone 16e</value>
      <webElementGuid>3128d681-a738-458a-8648-17d78ee14a9e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
