<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Generated by Katalon AI</description>
   <name>link_apple</name>
   <tag></tag>
   <elementGuidId>36f05f0e-54b7-4e60-b18c-9bfc8f804aa0</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[3]/nav[1]/div[1]/ul[1]/li[1]/ul[1]/li[1]/a[1]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(1) > [class=&quot;horizontal-menu__element\ is-link\ is-child&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'horizontal-menu__element is-link is-child' and @href = '/category/phone-apple' and (text() = 'Apple' or . = 'Apple')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Apple&quot;s] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>horizontal-menu__element is-link is-child</value>
      <webElementGuid>3350b1c2-b21c-4c51-9aca-7465c7d64571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/category/phone-apple</value>
      <webElementGuid>0734adaa-7cb9-436b-9ef6-aa8e859732cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apple</value>
      <webElementGuid>317f33ac-4ec1-4091-bbd8-50af646aa6b4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
